export { default as Home } from './Home';
export { default as Services } from './Services';
export { default as PageNotFound } from './PageNotFound';
export { default as Consultancy } from './Consultancy';
export { default as HumanResources } from './HumanResources';
export { default as ImprotExport } from './ImprotExport';
export { default as ServiceDetail } from './ServiceDetail';
export { default as Login } from './Login';
export { default as SignUp } from './SignUp';
