export { default as Navbar } from './NavbarComp/Navbar';
export { default as Footer } from './FooterComp/Footer';
export { default as Carousel } from './HomeComp/Carousel';
export { default as Services } from './HomeComp/Services';
export { default as Gateway } from './HomeComp/Gateway';
export { default as HeroBanner } from './HomeComp/HeroBanner';
export { default as ConnectWorld } from './Connect/ConnectWorld';
export { default as CotactUs } from './Connect/CotactUs';
export { default as OurCompany } from './Connect/OurCompany';
